### ISSUE TITLE
Include Functionality

### ISSUE THREAD

**Issue by ccarrero301** [Baune8D/linqbuilder#4]
How would you use include in EF core with specification?

**Comment by Baune8D** [comment]
LinqBuilder includes extensions for ```IQueryable```, so you should be able to use ```Include``` without any problems.

```csharp
ISpecification<Person> firstnameIsFoo = Spec<Person>.New(p => p.Firstname == "Foo");
var result = sampleDbContext.Include(p => p.ChildEntity).Where(firstnameIsFoo);
```
